blog/base/urls.py
from django.urls import path

from . import views

# app_name = 'base'

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about,name="about"),
    path('contact/',views.contact,name="contact")
]

blog/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('post/',include('posts.urls')),
    path('user/',include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post, name="list"),
    path("getposts", views.getposts, name="getposts"),
    # path("getimages", views.getimages, name="getimages"),
    path("getmembers", views.getmembers, name="getmembers"),
    path("getmember/<int:id>", views.getmember, name="getmember"),
    path("update_member_to/<int:id>", views.update_member_to, name="update_member_to"),
    path("member-addres", views.member_address, name="member_address"),
    path("getaddress/<int:id>", views.getaddress, name="getaddress"),
    path("member-data/<int:id>", views.memberdetails, name="memberdetails"),
    path("delete/<int:id>", views.delete_member, name="delete"),
    path("new-post/", views.post_new, name="new-post"),
    path("create-member", views.create_member, name="create-member"),
    # path("users-view", views.users_view, name="users-view"),
    path("new-feed", views.new_feed, name="new-feed"),
    path("get-post/<int:id>", views.post_page, name="post_page"),
    # path("<slug:slug>", views.post_page, name="page"),
    path("delete-post/<int:id>", views.delete_post, name="delete_post"),
]

blog/users/urls.py
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path('',views.user,name="user"),
    path('register/',views.register_user,name="register"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),

]

blog/base/models.py
from django.db import models

# Create your models here.

blog/base/views.py
from django.shortcuts import render


def home(request):
    return render(request,'base/home.html')

def about(request):
    return render(request,'base/about.html')

def contact(request):
    return render(request,'base/contact.html')

blog/templates/base/about.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<nav>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'posts:list' %}">Post</a></li>
        {% else %}
        <li><a href="{% url 'users:user' %}">User</a></li>
      
        {% endif %}

    </ul>

</nav>

<!-- <p>About</p> -->
{% endblock %}

blog/templates/base/contact.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<nav>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'posts:list' %}">Post</a></li>
        {% else %}
        <li><a href="{% url 'users:user' %}">User</a></li>
        {% endif %}
    </ul>
</nav>

<p>Contact</p>
{% endblock %}

blog/templates/base/home.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<nav>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'posts:list' %}">Post</a></li>
        {% else %}
        <li><a href="{% url 'users:user' %}">User</a></li>
      
        {% endif %}
    </ul>
</nav>


<p>Home</p>
{% endblock %}