blog/base/urls.py
from django.urls import path

from . import views

# app_name = 'base'

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about,name="about"),
    path('contact/',views.contact,name="contact")
]

blog/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('post/',include('posts.urls')),
    path('user/',include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post, name="list"),
    path("getposts", views.getposts, name="getposts"),
    # path("getimages", views.getimages, name="getimages"),
    path("getmembers", views.getmembers, name="getmembers"),
    path("getmember/<int:id>", views.getmember, name="getmember"),
    path("update_member_to/<int:id>", views.update_member_to, name="update_member_to"),
    path("member-addres", views.member_address, name="member_address"),
    path("getaddress/<int:id>", views.getaddress, name="getaddress"),
    path("member-data/<int:id>", views.memberdetails, name="memberdetails"),
    path("delete/<int:id>", views.delete_member, name="delete"),
    path("new-post/", views.post_new, name="new-post"),
    path("create-member", views.create_member, name="create-member"),
    # path("users-view", views.users_view, name="users-view"),
    path("new-feed", views.new_feed, name="new-feed"),
    path("get-post/<int:id>", views.post_page, name="post_page"),
    # path("<slug:slug>", views.post_page, name="page"),
    path("delete-post/<int:id>", views.delete_post, name="delete_post"),
]

blog/posts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body  = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png',blank=True)
    auther = models.ForeignKey(User, on_delete=models.CASCADE,default=None) #on delete is requirecd telling the database how to handle if the relationship or user is delete, casecade will delete all post made by a user if the user is deleted or removed
    
    def __str__(self):
        return self.title


     

class Members(models.Model):
    username = models.CharField(max_length=75)
    email = models.CharField(max_length=200,null=True)
    avatar = models.ImageField(null=True)
    age = models.IntegerField()
    posts = models.ManyToManyField(Post,blank=True,related_name="members")
    created_at = models.DateTimeField(auto_now_add=True, null=True, editable=False)
    updated_at = models.DateTimeField(auto_now = True, null=True)

    class Meta:
        ordering = ['-updated_at','-created_at']

    def __str__(self):
        return self.username



class Address(models.Model):
    member_id  = models.OneToOneField(Members,on_delete=models.CASCADE,default=None)
    street = models.CharField(max_length=75)
    city = models.CharField(max_length=75)
    country  = models.CharField(max_length=75)

    def __str__(self):
        return self.street

blog/posts/forms.py
from django import forms

from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','banner']

class MembersForm(forms.ModelForm):

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['username'].required = True     

    class Meta:
        model = models.Members
        fields = ['username','email','avatar','age']
        

class AddressForm(forms.ModelForm):
    class Meta:
        models = models.Post
        field = ['member_id','street','city','country']

blog/posts/views.py
import json
import os
import time
from pathlib import Path
from pprint import pprint

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.http import HttpRequest, JsonResponse
from django.shortcuts import HttpResponse, redirect, render

from config.settings import MEDIA_URL

from . import forms
from .forms import MembersForm
from .models import Address, Members, Post
from .serializers import (
    AddressSerializer,
    MemberSerializer,
    PostCreateSerializer,
    PostSerializer,
)

# Create your views here.


def post(request):
    return render(request, "post/post.html")


def getposts(request):
    posts = Post.objects.all()
    serializer = PostSerializer(posts, many=True)
    return JsonResponse({"post": serializer.data})


def getmembers(request):
    username = (
        request.GET.get("username") if request.GET.get("username") != None else ""
    )
    age = request.GET.get("age") if request.GET.get("age") != None else ""

    if age:
        start_value = age.split("_")[0]
        end_value = age.split("_")[1]
    q_obj = Q()

    if username:
        q_obj = Q(username__icontains=username) | Q(email__icontains=username)

    if age:
        q_obj &= Q(age__range=(start_value, end_value))

    # print(q_obj,"q_obj")

    members = Members.objects.filter(q_obj)

    # serilization

    serializer = MemberSerializer(members, many=True)
    return JsonResponse({"members": serializer.data})


def getmember(request, id):
    member = Members.objects.filter(id=id).first()
    serialize = MemberSerializer(member)
    return JsonResponse(serialize.data)


def update_member_to(request: HttpRequest, id: int):
    try:
        member = Members.objects.filter(id=id).first()
    except:
        member = None

    if request.method == "POST":
        if not member:
            return JsonResponse({"details": "no member found"}, status=404)

        payload: dict = json.loads(request.body)
        member.posts.clear()

        serializer = MemberSerializer(member, data=payload)
        if serializer.is_valid():
            serializer.save()
            print(serializer.data)

            return JsonResponse(serializer.data)

        return JsonResponse(serializer.errors, status=400)


def member_address(request: HttpRequest):
    if request.method == "POST":
        payload: dict = json.loads(request.body)

        member = Members.objects.filter(id=payload.get("member").strip()).first()

        if not member:
            return JsonResponse({"detail": "member is not present"}, status=404)

        serializer = AddressSerializer(payload)

        street = payload.get("street").strip()
        city = payload.get("city").strip()
        country = payload.get("country")

        address, _ = Address.objects.get_or_create(member_id=member)
        address.street = street
        address.city = city
        address.country = country
        address.save()
        serializer = AddressSerializer(address)
        return JsonResponse(serializer.data)


def getaddress(request, id):
    address = Address.objects.filter(member_id=id).first()
    if not address:
        return JsonResponse({"detail": "address not found"}, status=404)

    serializer = AddressSerializer(address)
    return JsonResponse(serializer.data)


def new_feed(request: HttpRequest):
    if request.method == "POST":
        payload = request.POST.dict()
        payload["auther"] = request.user.pk

        serilizer = PostCreateSerializer(data=payload)
        if serilizer.is_valid():
            serilizer.save()
            return JsonResponse(serilizer.data, status=201)
        return JsonResponse(serilizer.errors, status=400)

    return render(request, "post/add_feed.html")


def create_member(request: HttpRequest):
    if request.method == "POST":
        payload: dict = json.loads(request.body)
        serializer = MemberSerializer(data=payload)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse({"message": "User Created"}, status=201)
        return JsonResponse(serializer.errors, status=400)

    posts = Post.objects.all()
    context = {"posts": posts}

    return render(request, "post/user_define.html", context)


def validateEmail(email):
    from django.core.exceptions import ValidationError
    from django.core.validators import validate_email

    try:
        validate_email(email)
        return True
    except ValidationError:
        return False


def memberdetails(request, id):
    if request.method == "POST":
        return JsonResponse({})

    member = Members.objects.filter(id=id).first()
    if member:
        posts = member.posts.all()
        if posts.exists():
            context = {"posts": posts, "member": member}
            return render(request, "post/member.html", context)
        context = {"member": member}
        return render(request, "post/member.html", context)
    return render(
        request, "post/member.html", {"error": "No posts related to this member"}
    )


def delete_member(request, id):
    try:
        member = Members.objects.filter(id=id).first()
    except:
        member = None

    if member:
        member.delete()
        return HttpResponse("Member Deleted")
    return HttpResponse("Member not found")


def post_page(request, id):

    post = Post.objects.filter(id=id).first()
    members = post.members.all()
    context = {"post": post, "members": members}

    # post = Post.objects.get(slug=slug)

    return render(request, "post/post_page.html", context)

    q = request.GET.get("q") if request.GET.get("q") != None else ""


def delete_post(request, id):

    post = Post.objects.get(id=id)
    if post:
        post.delete()
    return redirect("home")


# use authentication  only the person who logged in
def post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(
            request.POST, request.FILES
        )  # FILES added because of adding image
        # save with user
        newpost = form.save(commit=False)
        newpost.auther = request.user
        newpost.save()
        return redirect("posts:list")
    form = forms.CreatePost()
    return render(request, "post/post_new.html", {"form": form})

blog/templates/post/add_feed.html
{% extends 'main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<form id="post-form">
    {% csrf_token %}
    <h3>Title</h3> <input type="title" name="title" id="title"><br>
    <h3>Body</h3> <input type="body" name="body" id="body"><br>
    <h3>Banner</h3> <input type="file" name="banner" id="banner"><br>

    <!-- <select name="posts" id="posts">
        <option value=""></option>
       
      </select> -->
    <button type="button" onclick="createPost()">Submit</button>
</form>




<script>

// $(document).on('submit','#post-form',function(e)
// {
//     const form = document.getElementById("post-form'")
//     const formData =  new  FormData(form)
//     formObjectData = Object.fromEntries(formData)
//     for([key,value] of formData.entries()){
//         console.log(key,value);
        
//     }
//     e.preventDefault();;

//     $.ajax({
//         type : 'POST',
//         url : "new-feed",
//         data :formData,
//         headers: {
//             "X-CSRFToken" : `{{csrf_token}}`
//         },
//         success : function(data){
//             alert(data)
//         },
//         error: function(data){
//             alert("Something wrong")
//         }
//     })


// })





// $(document).on('submit','#post-form',function(e)
// {
//     e.preventDefault();

//     $.ajax({
//         type:'POST',
//         url : "new-feed",
//         data : {

//             title : $('#title').val(),
//             body:$('#body').val(),
//             banner:$('#banner').val(),
//             csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),

//         },
//         success: function(data){
//             alert(data);
//         }
//     });

// });

// var total = 5;
// for(var i = 1; i<= total ; i++){
//     var added = document.createElement('option');
//     var select1 = $("#posts")
//     added.value = i
//     added.innerHTML = i
//     select1.append(added)
// }

</script>
<script>
    const createPost = async ()=>{
        const form = document.getElementById('post-form')
        const formData = new FormData(form)
        
        const postData = {}
        for([key,value] of formData.entries()){
        postData[key] = value;
        
    }        
        try {
           const response = await axios.post("new-feed",formData,{

            headers:{
                "X-CSRFToken" : `{{csrf_token}}`

            },
            success : function(data){
                alert(data)
            }
           });
        }
        catch (error){
        console.log(error);        
        }
    }
</script>

{% endblock %}

blog/templates/post/member.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<style>
    .home-container {
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<div class="home-container">
    <div>
        <h2 id="member-id" style="display: none;">{{  member.id }}</h2>
        <h2  style="text-align: center;">Member : {{ member.username }}</h2>
        <h4  style="text-align: center;">Email : {{ member.email  }} </h4>
        <h4  style="text-align: center;">Age : {{ member.age }}</h4>
    </div>
    <div>
        <h2 style="text-align: center;">Posts.....</h2>
        {% for post in posts %}
        <p>{{ post.title }}</p>  
        
        <a href="{% url 'posts:post_page' post.id %}">
            <img class="banner" style="margin-left: 170px;" src="{{ post.banner.url }}" alt="{{ post.title }}" />
        </a>
        
    {% endfor %}
    

    </div>

    <div>
        <form id="address-form" method="">
        {% csrf_token %}    

        <input type="hidden" name="member" id="member">
        <h3>Street</h3> <input type="text" name="street" id="street" readonly><br>
        <h3>City</h3> <input type="text" name="city" id="city" readonly><br>
        <h3>County</h3> <input type="text" name="country" id="country" readonly> <br>
        <button type="button" id="edit-btn" onclick="editAddress()" style="display: block;">edit</button>
        <button type="button" id="submit-btn" onclick="submitAddress()" style="display: none;">submit</button>

    </form>
    </div>
</div>
<script>
    const BASE_URL = 'http://localhost:8001'
    var memberId = document.querySelector("#member-id").textContent
    </script>
<script>
    
    const editAddress = ()=> {

        const editBtn = document.querySelector("#edit-btn")
        editBtn.style.display = "none"
        const subBtn = document.querySelector("#submit-btn")
        subBtn.style.display = "block"

        
        const member = document.querySelector("[name='member']")
        const street = document.querySelector("[name='street']")
        const city = document.querySelector("[name = 'city']")
        const counrty = document.querySelector("[name = 'country']")

        street.removeAttribute("readonly")
        city.removeAttribute("readonly")
        counrty.removeAttribute("readonly")


        const memberId = document.querySelector("#member-id").textContent
        console.log(memberId);
        
        member.value = memberId
        console.log(member);


       
     
        
    }
    

    const fetchMemberAddress = ()=> {
           
        $.ajax ({
     
            type:'GET',
            url : `${BASE_URL}/post/getaddress/${memberId}`,
            success : function(response){
                const {street,city,country} = response

                const streetElm = document.querySelector("[name='street']")
                const cityElm = document.querySelector("[name='city']")
                const countryElm = document.querySelector("[name='country']")

                streetElm.value = street
                cityElm.value = city
                countryElm.value =  country


            }
            
        })
    }
    fetchMemberAddress()
    const submitAddress = ()=> {
        
            const addressForm = document.getElementById("address-form");
            const formData = new FormData(addressForm)
            const dataObject = Object.fromEntries(formData.entries())

            $.ajax ({
                type : "POST",
                url : `${BASE_URL}/post/member-addres`,
                data: JSON.stringify(dataObject),
                headers: {
                    "X-CSRFToken" : `{{csrf_token}}`
                },
                success : function(response){
                    
                    alert("address created")
                },
                error : function(data){
                    alert("Something Went wrong")
                }
            })
            
        
        
    }
</script>



{% endblock %}

blog/templates/post/post.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<div id="post" style="text-align: center;">
</div>
<div id="media-images">
</div>
<script>
var BASE_URL= 'http://localhost:8001'
</script>

<script>
$(document).ready(function() {
    $.ajax({
        type: 'GET',
        url: `${BASE_URL}/post/getposts`,
        success: function(response) {
            
            
            $("#media-images").empty();
            const posts = response.post;
            console.log(posts);
            
            
            
            posts.forEach((post,i) =>{
                const {id,title,banner} = post
                console.log(id,title,banner);
                
                
            const data = `<h3>${title}</h3> `
            $("#post").append(data)
            const PostImageData = `<a href="/post/get-post/${id}"> <img src="${banner}" style="width: 30%; height: 30%;"> </a>`;
            $("#post").append(PostImageData)
            })
            
        }
    });
})
</script>

<!-- for adding image to the template from base dir -->
<!-- <script>
$(document).ready(function() {
    $.ajax({
        type: 'GET',
        url: 'http://localhost:8001/post/',
        success: function(response) {
            $("#media-images").empty();
            const images = response.img;
            for (var img in images)
        {
            console.log(images[img])
            const data = `<img src="/${images[img]}" style="width: 100%; height: 100%;">`;
            $("#media-images").append(data)
        }
        }
    });
});
</script> -->



<!-- </div> -->
<!-- <script>
$(document).ready(function() {
    $.ajax({
        type: 'GET',
        url: 'http://localhost:8001/post/getposts',
        success: function(response) {
            console.log(response);
            
            $("#media-images").empty();
            const images = response.img;
            
            for (var img in images)
        {
            console.log(images[img])
            const data = `<img src="/${images[img]}" style="width: 100%; height: 100%;">`;
            $("#media-images").append(data)
        }
        }
    });
});

</script> -->

<!-- for adding image to the template from base dir -->
<!-- <script>
$(document).ready(function() {
    $.ajax({
        type: 'GET',
        url: 'http://localhost:8001/post/',
        success: function(response) {
            $("#media-images").empty();
            const images = response.img;
            for (var img in images)
        {
            console.log(images[img])
            const data = `<img src="/${images[img]}" style="width: 100%; height: 100%;">`;
            $("#media-images").append(data)
        }
        }
    });
});
</script> -->





<!-- <button id="button">Click</button> 
<input type="number" name="number" id="number">

<div id="image-doc" style="display: flex;flex-wrap: wrap;gap: 12px;">
    
</div>
<script>

const fetchDog = document.getElementById('button')
var BASE_URL = "https://dog.ceo/api"
fetchDog.addEventListener('click',()=>{
    let getImgNum = document.getElementById("number").value
    $.ajax({
        type:'GET',
        url : `${BASE_URL}/breeds/image/random/${getImgNum}`,
        success:function(response){
            $("#display-data").empty();
            {

 const dogImg = response.message
            dogImg.forEach(path => {
                const data =  
                `<div style="min-width:300px;height:300px"> <img src="${path}" alt="Dog Image" style="width: 100%;height:100%; object-fit:cover"> </div>`
                $('#image-doc').append(data)
            });

            }
        }
    })
});  -->
<!-- </script>  -->

<!-- <button id="button">Click</button>
<input type="number" name="number" id="number">

<div id="image-doc" style="display: flex;flex-wrap: wrap;gap: 12px;">
    
</div>
<script>

const fetchDog = document.getElementById('button')
var BASE_URL = "https://dog.ceo/api"
fetchDog.addEventListener('click',()=>{
    let getImgNum = document.getElementById("number").value
    $.ajax({
        type:'GET',
        url : `${BASE_URL}/breeds/image/random/${getImgNum}`,
        success:function(response){
            $("#display-data").empty();
            {

 const dogImg = response.message
            dogImg.forEach(path => {
                const data =  
                `<div style="min-width:300px;height:300px"> <img src="${path}" alt="Dog Image" style="width: 100%;height:100%; object-fit:cover"> </div>`
                $('#image-doc').append(data)
                
            });

            }
           

        }
    })


});
</script> -->






<!-- for show a random image when clicking a button  -->
<!-- <div>
    <img src="" id="dogimage" alt="Dog image" style="width: 500px; height: auto;">
</div>

<button id="button">Fetch</button> -->
<!-- <script>
    const fetchDog = document.getElementById('button')
    var BASE_URL = "https://dog.ceo/api"
    
    fetchDog.addEventListener("click",()=>{
            $.ajax({
            type:'GET',
            url: `${BASE_URL}/breeds/image/random`,
            success:function(response){
                const dogImg = response.message
                $('#dogimage').attr('src',dogImg)
                console.log(response.message)
    
    
                // const dogimg = response
            }
    
        })
    })
    
    </script> -->
    

</section>
{% endblock %}

blog/templates/post/post_new.html
{% extends 'main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title%}
{% endblock %} 
{% block content %}
<section>
<h1>New Post</h1>
<form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post"   
enctype="multipart/form-data">
<!-- The action attribute specifies where the form data should be sent when the form is submitted.  -->
{% csrf_token %}
{% render_field form.title placeholder="title" class+="form-control" %}
<br/>
{% render_field form.body placeholder="body" class+="form-control" %}
<br/>
{% render_field form.banner placeholder="slug" class+="form-control" %}
<br/>
{% render_field form.slug placeholder="slug" class+="form-control" %}
<br/>
<button class="form-submit">Add</button>
</form>
</section>
{% endblock %}

blog/templates/post/post_page.html
{% extends 'main.html' %}
{% load static %}

{% block title%}
{% endblock %} 
{% block content %}


<section>
  
    <h1>{{ post.title }}</h1>
      <p>{{ post.date |timesince}}</p>
      <p>{{ post.body }}</p>
      <br/>
      <img class="banner" style="    margin-left: 555px;" src="{{ post.banner.url }}"alt = "{{post.title }}"/>
      <h3 style="text-align: center;">Created By : {{ post.auther }}</h3>
      <a href="{% url 'posts:delete_post' post.id %}">
        <button style="background-color: red; color: white; border: none; padding: 10px 20px; cursor: pointer; margin-left: 900px;" name="Delete" aria-label="Delete Post" >
          Delete
        </button>
      </a>
      <h3 style="text-align: center;" >Members</h3>
      {% for member in members %}
          <a href="{% url  'posts:memberdetails' member.id %}"><p >{{ member.username }} </p></a>
      {% endfor %}

</section>

{% endblock %}
    
</form>