blog/base/urls.py
from django.urls import path

from . import views

# app_name = 'base'

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about,name="about"),
    path('contact/',views.contact,name="contact")
]

blog/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('post/',include('posts.urls')),
    path('user/',include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post, name="list"),
    path("getposts", views.getposts, name="getposts"),
    # path("getimages", views.getimages, name="getimages"),
    path("getmembers", views.getmembers, name="getmembers"),
    path("getmember/<int:id>", views.getmember, name="getmember"),
    path("update_member_to/<int:id>", views.update_member_to, name="update_member_to"),
    path("member-addres", views.member_address, name="member_address"),
    path("getaddress/<int:id>", views.getaddress, name="getaddress"),
    path("member-data/<int:id>", views.memberdetails, name="memberdetails"),
    path("delete/<int:id>", views.delete_member, name="delete"),
    path("new-post/", views.post_new, name="new-post"),
    path("create-member", views.create_member, name="create-member"),
    # path("users-view", views.users_view, name="users-view"),
    path("new-feed", views.new_feed, name="new-feed"),
    path("get-post/<int:id>", views.post_page, name="post_page"),
    # path("<slug:slug>", views.post_page, name="page"),
    path("delete-post/<int:id>", views.delete_post, name="delete_post"),
]

blog/users/urls.py
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path('',views.user,name="user"),
    path('register/',views.register_user,name="register"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),

]

blog/users/models.py
from django.db import models

# Create your models here.

blog/users/views.py
import json
from pprint import pprint

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpRequest, JsonResponse
from django.shortcuts import redirect, render

from .serializers import RegisterUserSerializer, LoginUserSerializer

# from .serializers import RegisterUser


def user(request):
    return render(request, "users/user.html")


def register_user(request: HttpRequest):
    if request.method == "POST":
        payload: dict = json.loads(request.body)
        serializer = RegisterUserSerializer(data=payload)
        if serializer.is_valid():
            user = serializer.save()
            login(request, user)
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

    return render(request, "users/user_register.html", {})


def login_user(request):
    if request.user.is_authenticated:
        return redirect("posts:list")
    if request.method == "POST":
        payload: dict = json.loads(request.body)
        serializer = LoginUserSerializer(data=payload)

        if serializer.is_valid():
            data = serializer.data
            username = data["username"]
            password = data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return JsonResponse({})
            return JsonResponse({"detail": "invalid credential"}, status=401)
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})


def logout_user(request):
    if request.method == "POST":
        logout(request)
        return redirect("home")

    return render(request, "users/logout.html")

blog/templates/users/login.html
{% extends 'main.html' %}
{% load static%}

{% block content %}
<p>Login User</p>


    <form id="login_form">

        {% csrf_token %}
        <div>
            <h3>Username</h3><input type="text" name="username" id="username"><br>
        </div>
        <div>
            <h3>Password</h3><input type="password" name="password" id="password"><br>
        </div>
        <button type="button" id="button" onclick="loginUser()">Submit</button>
    </form>

    <script>
        const loginUser = async () => {

            // const form = document.querySelector("form[class='login_form']");
            const form = document.getElementById("login_form");

            const formData = new FormData(form)
            const formDataObject = Object.fromEntries(formData)

            try {
                const response = await axios.post("{% url 'users:login' %}", formDataObject, {
                    headers: {
                        "X-CSRFToken": `{{csrf_token}}`
                    },
                });

                if(response.status===200){
                    window.location.href = "{% url 'posts:list' %}"
                }
            }
            catch (error) {
                console.log(error);
            }
        }
    </script>
    {% endblock %}

blog/templates/users/logout.html
{% extends 'main.html' %}
{%  load static%}

{% block content %}
<p>Log Out</p>
<form class="logout" action="{% url 'users:logout' %}" method="post">  
{% csrf_token %}
{{ form }}<button class="form-submit">Logout</button>
</form>
{% endblock %}

blog/templates/users/user.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<p>User</p>
<nav>
    <ul>
        <li><a href="{% url 'users:register' %}">Register</a></li>


    </ul>
</nav>

{% endblock %}

blog/templates/users/user_register.html
{% extends 'main.html' %}
{%  load static %}

{% block content %}
<p>Register</p>
<div>
    <form class="user-form">
        {% csrf_token %}
        <div>
            <h3>Username</h3><input type="text" name="username" id="username" ><br>
            <span class="error"></span>
        </div>
    <div>
        <h3>Password</h3><input type="password" name="password" id="password">
        <span class="error"></span>
    </div>
    <div>
        <h3>Confirm Password</h3><input type="password" name="confirm_password" id="password2">
        <span class="error"></span>
    </div>
     <button type="button" id="button" onclick="createUser()">Submit</button>
    </form>

</div>

<script>
const createUser = async ()=> {

    const form = document.querySelector(".user-form")
    console.log(form);
    
    const formData = new FormData(form)

    const formObjectData = Object.fromEntries(formData)

    for (const [key, value] of formData.entries()) {
            const elem = document.querySelector(`[name="${key}"]`);
            if (elem) {
                elem.removeAttribute("style");
                const errorElem = elem.parentElement.querySelector(".error");
            if (errorElem) {
              errorElem.textContent = "";
                  }
              }
            }
try {
    const response = await axios.post('/user/register/', formObjectData, {
        headers: {
            "X-CSRFToken": `{{csrf_token}}`
        },
    });
    if (response.status == 201){
        alert("User Registration Completed")
        window.location.href = "{% url 'posts:list' %}"  
    } 
} 
catch (error) {
    const response = error.response.data        
    if(response){
        for(const [key,value] of Object.entries(response)) {
            const elm = document.querySelector(`[name="${key}"]`)            
            elm.style.border = "1px solid red"
            elm.parentElement.querySelector(".error").textContent = value
        }
    }
}
}
</script>


{% endblock %}



<!-- 

<form class="form-with-validation" action="/user/register/" method="post">  
    {% csrf_token %} 
    
    {{ form }}<button class="form-submit">Submit </button>
    </form>  -->